from tkinter import *
from PIL import Image,ImageTk
import subprocess
def click(event):
    if((((event.x)>=583)and(event.x<=596))and((event.y>=28)and(event.y<=40))):
        subprocess.Popen(["Python","sudoku.py"])
        root.destroy()
root = Tk()
root.geometry("1280x648")
root.config(bg="white")
a = Label(text="This is a sudoku solver which solves sudoku\nEnter values correctly or bad things might happen\nIdea by -> Chirag\nDeveloped by -> Chirag\nDesigns ->Hiyanshu",font=("IBM Plex Sans",14,"bold"),bg="white",fg="black")
a.pack()
a.place(x=350,y=150)
b = Label(text="Contact us\n \nChirag -> 8239713575                 Hiyanshu -> 7597965838",font=("IBM Plex Sans",14,"bold"),bg="white",fg="black")
b.pack()
b.place(x=350,y=350)
c= Label(text="    @Chirag_CR13                                       @hiyanshu37",font=("IBM Plex Sans",14,"bold"),bg="white",fg="black")
c.pack()
c.place(x=350,y=420)
home = Label(text="Home",font=("IBM Plex Sans",5),fg="#5F7367",bg="#A8D94E")
home.pack()
home.place(x=860,y=50)
img2 = Image.open("upper_bar.png")
img3 = img2.resize((650,65))
bar = ImageTk.PhotoImage(img3)
ubar=Label(image=bar,borderwidth=0)
ubar.pack()
root.bind('<Button-1>',click)
ubar.place(x=280,y=10)
img = Image.open("Hiyanshu.png")
img = img.resize((100,120))
img1 = ImageTk.PhotoImage(img)
about = Label(text="About Us",font=("IBM Plex Sans",5),fg="#5F7367",bg="#A8D94E")
about.pack()
about.place(x=880,y=50)
PaG = Label(image=img1)
PaG.pack()
PaG.place(x=720,y=450)
img5 = Image.open("me.jpg")
img5 =img5.resize((100,120))
img4 = ImageTk.PhotoImage(img5)
me =Label(image=img4)
me.pack()
me.place(x=400,y=450)
e = Label(text="Please note that this window is not designed by Hiyanshu",bg="white")
e.pack()
e.place(x=430,y=600)
root.mainloop()